In [1]:
import torch

c:\Users\darcy\Documents\Projects\my_llm\env\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),

            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),

            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [3]:
model = NeuralNetwork(50, 3)

In [4]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [5]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(num_params)

2213


In [6]:
print(model.layers[0].weight)

Parameter containing:
tensor([[ 0.0324,  0.0310,  0.0040,  ..., -0.0018, -0.0323, -0.0629],
        [-0.1403,  0.0108, -0.0351,  ...,  0.1252,  0.0892,  0.1004],
        [-0.0444,  0.1316, -0.1273,  ...,  0.1219, -0.0709, -0.0167],
        ...,
        [-0.0371, -0.0862,  0.1411,  ..., -0.1283,  0.0579, -0.0043],
        [-0.1126, -0.0050,  0.0902,  ...,  0.1380,  0.0153, -0.1326],
        [ 0.1387,  0.0373, -0.0032,  ...,  0.1284, -0.0510,  0.0814]],
       requires_grad=True)


In [7]:
torch.manual_seed(123)
X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[ 0.0743, -0.2161,  0.0947]], grad_fn=<AddmmBackward0>)


In [8]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1)
print(out)

tensor([[0.3612, 0.2702, 0.3686]])
